### ISSUE TITLE
Update Issues to be more clear.

### ISSUE THREAD

**Issue by jacebenson** [jacebenson/x_8821_atf#31]
#1 and #30 are good examples of how concise the issues here should be.
We should update the other issues;
- [ ] #17 - Make new Issue to list specific tests
- [ ] #18 - Update to list specific tests
- [ ] #19 - Update to list specific tests
- [ ] #20 - Update to list specific tests
- [ ] #21 - Update to list specific tests
- [ ] #22 - Update to list specific tests
- [ ] #23 - Split into issues for each part, and then list specific tests
- [ ] #24 - Update to list specific tests
- [ ] #25 - Split into issues for each part, and then list specific tests
- [x] #26 - Update to list specific tests
